import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Movie } from "../types";

export const getServerSideProps: GetServerSideProps = async () => {
  const resp = await fetch("https://srsku.deno.dev/api/v1/movie?limit=12");
  const { data } = await resp.json();

  return {
    props: {
      movies: data,
    },
  };
};

interface IHomePage {
  movies: Array<Movie>;
}

const Home: NextPage<IHomePage> = ({ movies }) => {
  return (
    <div className="p-5">
      <Head>
        <title>Movie App - SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-poppins text-3xl mx-auto text-center mb-10 text-green-500 font-semibold">
        Movies App - SSR
      </h1>

      <div className="grid grid-cols-4 gap-5 mx-auto">
        {movies.map((movie) => (
          <Link passHref key={movie.slug} href={`/movies/${movie.slug}`}>
            <a className="flex items-start space-x-5 appearance-none">
              <div className="w-48">
                <Image
                  alt={movie.title}
                  src={movie.poster}
                  width={500}
                  height={800}
                  objectFit="cover"
                  loading="lazy"
                />
              </div>
              <div>
                Title: {movie.title}
                <br />
                Director: {movie.director}
                <br />
                Release Date: {new Date(movie.release).toUTCString()}
              </div>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Home;
