import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Movie } from "../../types";

interface IDetailMovie {
  movie: Movie;
}

export const getStaticPaths: GetStaticPaths = async () => {
  const resp = await fetch("https://srsku.deno.dev/api/v1/movie?limit=12");
  const { data } = await resp.json();

  return {
    paths: data.map((movie: Movie) => ({
      params: { slug: movie.slug.toString() },
    })),
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const resp = await fetch(
    `https://srsku.deno.dev/api/v1/movie/${params?.slug}/one`
  );
  const { data } = await resp.json();

  return {
    props: {
      movie: data,
    },
    revalidate: 10,
  };
};

const DetailMovie: NextPage<IDetailMovie> = ({ movie }) => {
  return (
    <div className="p-5 w-full h-screen">
      <Head>
        <title>{movie.title} - SSG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center h-full space-x-5 appearance-none mx-auto w-full">
        <div className="w-48">
          <Image
            alt={movie.title}
            src={movie.poster}
            width={500}
            height={800}
            objectFit="cover"
            loading="lazy"
          />
        </div>
        <div>
          Title: {movie.title}
          <br />
          Director: {movie.director}
          <br />
          Release Date: {new Date(movie.release).toUTCString()}
        </div>
      </div>
    </div>
  );
};

export default DetailMovie;
